plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
    id "me.modmuss50.mod-publish-plugin"
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    mixin {
        defaultRefmapName.set("${mod_id}.refmap.json")
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

publishMods { file = tasks.remapJar.archiveFile }

var env = System.getenv()

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact tasks.remapJar.archiveFile
            artifact(sourcesJar) {
                builtBy tasks.remapSourcesJar.archiveFile
            }

            artifactId = "${publish_name}-${name}"

            pom {
                name = "${publish_name}-${name}"
                description = "${description}"
                url = "${publish_repo}"

                scm {
                    connection = "git:${publish_repo}.git"
                    developerConnection = "git:${publish_repo}.git"
                    url = "${publish_repo}"
                }

                licenses {
                    license {
                        name = "MIT License"
                        url = "${publish_repo}/blob/master/LICENSE.txt"
                    }
                }

                developers {
                    developer {
                        id = "${publish_id}"
                        name = "${publish_author}"
                        email = "${publish_email}"
                    }
                }
            }
        }
    }

    repositories {
        maven {
            url = uri("https://nexus.resourcefulbees.com/repository/telepathicgrunt/")
            credentials {
                username env.MAVEN_USER
                password env.MAVEN_PASS
            }
        }
    }
}

task buildAndRelease{}
tasks.publish.mustRunAfter tasks.build
tasks.publishMods.mustRunAfter tasks.publish
tasks.buildAndRelease.dependsOn(tasks.build, tasks.publish, tasks.publishMods)