plugins {
    id 'java-library'
    id 'maven-publish'
}

base {
    archivesName = "${mod_id}"
    version = "${rootProject.mod_version}+${rootProject.minecraft_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
    withSourcesJar()
    withJavadocJar()
}

repositories {
    mavenCentral()
    // https://docs.gradle.org/current/userguide/declaring_repositories.html#declaring_content_exclusively_found_in_one_repository
    exclusiveContent {
        forRepository {
            maven {
                name = 'Sponge'
                url = 'https://repo.spongepowered.org/repository/maven-public'
            }
        }
        filter { includeGroupAndSubgroups('org.spongepowered') }
    }
    exclusiveContent {
        forRepositories(
                maven {
                    name = 'ParchmentMC'
                    url = 'https://maven.parchmentmc.org/'
                },
                maven {
                    name = "NeoForge"
                    url = 'https://maven.neoforged.net/releases'
                }
        )
        filter { includeGroup('org.parchmentmc.data') }
    }
    maven {
        name = 'BlameJared'
        url = 'https://maven.blamejared.com'
    }
}

// Declare capabilities on the outgoing configurations.
// Read more about capabilities here: https://docs.gradle.org/current/userguide/component_capabilities.html#sec:declaring-additional-capabilities-for-a-local-component
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations."$variant".outgoing {
        capability("$group:${base.archivesName.get()}:$version")
        capability("$group:$mod_id-${project.name}-${minecraft_version}:$version")
        capability("$group:$mod_id:$version")
    }
    publishing.publications.configureEach {
        suppressPomMetadataWarningsFor(variant)
    }
}

sourcesJar {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${mod_name}" }
    }
}

jar {
    from(rootProject.file('LICENSE')) {
        rename { "${it}_${mod_name}" }
    }

    manifest {
        attributes([
                'Specification-Title'   : mod_name,
                'Specification-Vendor'  : mod_author,
                'Specification-Version' : project.jar.archiveVersion,
                'Implementation-Title'  : project.name,
                'Implementation-Version': project.jar.archiveVersion,
                'Implementation-Vendor' : mod_author,
                'Built-On-Minecraft'    : minecraft_version
        ])
    }
}

processResources {
    var expandProps = [
            'version'                      : version,
            'group'                        : project.group, //Else we target the task's group.
            'minecraft_version'            : minecraft_version,
            'minecraft_version_range'      : minecraft_version_range,
            'fabric_version'               : fabric_api_version,
            'fabric_loader_version'        : fabric_loader_version,
            'mod_name'                     : mod_name,
            'mod_author'                   : mod_author,
            'mod_id'                       : mod_id,
            'description'                  : project.description,
            'neoforge_version'             : neoforge_version,
            'display_url'                  : display_url,
    ]

    filesMatching(['pack.mcmeta', 'fabric.mod.json', 'META-INF/mods.toml', 'META-INF/neoforge.mods.toml', '*.mixins.json']) {
        expand expandProps
    }
    inputs.properties(expandProps)
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifactId base.archivesName.get()
            from components.java
        }
    }
    repositories {
        maven {
            url System.getenv('local_maven_url')
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 21
}

Map<String, Map<String, String>> platformSettings = [
        "fabric": [
                "curse-id": "357304",
                "modrinth-id": "S1tbzJ6Y"
        ],
        "neoforge": [
                "curse-id": "357304",
                "modrinth-id": "S1tbzJ6Y"
        ]
]

Map<String, Map<String, Boolean>> platformDependencies = [
        "fabric": [
                "fabric-api": true
        ],
        "neoforge": []
] as Map<String, Map<String, Boolean>>

var env = System.getenv()
def uploadSettings = platformSettings.get(name)
def uploadDependencies = platformDependencies.get(name)

if (uploadSettings != null && uploadDependencies != null) {

    File changeLog = rootProject.file("CHANGELOG.md")
    String changelogText = changeLog.exists() ? changeLog.text : ""

    publishMods {
        file = tasks.jar.archiveFile
        type = STABLE
        changelog = changelogText

        displayName = "${mod_name} v${mod_version} ${name.capitalize()}"
        version = "${project.version}-${name}"
        modLoaders.add(name as String)

        if (env.CURSEFORGEKEY) {
            curseforge {
                accessToken = env.CURSEFORGEKEY
                projectId = uploadSettings["curse-id"]
                minecraftVersions.add(minecraft_version)

                if (uploadDependencies.size() > 0) {
                    uploadDependencies.each { dep, required ->
                        if (required) {
                            requires(dep)
                        }
                        else {
                            optional(dep)
                        }
                    }
                }
            }
        }

        if (env.MODRINTH_TOKEN) {
            modrinth {
                accessToken = env.MODRINTH_TOKEN
                projectId = uploadSettings["modrinth-id"]
                minecraftVersions.add(minecraft_version)

                dependencies {
                    uploadDependencies.each { dep, required ->
                        if (required) {
                            requires(dep)
                        } else {
                            optional(dep)
                        }
                    }
                }
            }
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact tasks.jar.archiveFile
            artifact(sourcesJar) {
                builtBy tasks.sourcesJar.archiveFile
            }

            artifactId = "${publish_name}-${name}"

            pom {
                name = "${publish_name}-${name}"
                description = "${description}"
                url = "${publish_repo}"

                scm {
                    connection = "git:${publish_repo}.git"
                    developerConnection = "git:${publish_repo}.git"
                    url = "${publish_repo}"
                }

                licenses {
                    license {
                        name = "MIT License"
                        url = "${publish_repo}/blob/master/LICENSE.txt"
                    }
                }

                developers {
                    developer {
                        id = "${publish_id}"
                        name = "${publish_author}"
                        email = "${publish_email}"
                    }
                }
            }
        }
    }

    repositories {
        maven {
            url = uri("https://nexus.resourcefulbees.com/repository/telepathicgrunt/")
            credentials {
                username env.MAVEN_USER
                password env.MAVEN_PASS
            }
        }
    }
}