plugins {
    // https://fabricmc.net/develop/
    id 'fabric-loom' version '1.8-SNAPSHOT' apply false

    // https://projects.neoforged.net/neoforged/moddevgradle
    id 'net.neoforged.moddev' version '2.0.49-beta' apply false

    // https://modmuss50.github.io/mod-publish-plugin/#changelog
    id "me.modmuss50.mod-publish-plugin" version "0.7.4"
}

tasks.register('buildAndReleaseAll') {
    dependsOn(':neoforge:buildAndRelease', ':fabric:buildAndRelease')
}