plugins {
    // https://fabricmc.net/develop/
    id 'fabric-loom' version '1.8-SNAPSHOT' apply false

    // https://projects.neoforged.net/neoforged/moddevgradle
    id 'net.neoforged.moddev' version '2.0.49-beta' apply false

    // https://modmuss50.github.io/mod-publish-plugin/#changelog
    id "me.modmuss50.mod-publish-plugin" version "0.8.4"
}

publishMods {
    File changeLog = rootProject.file("CHANGELOG.md")
    String changelogText = changeLog.exists() ? changeLog.text : ""

    changelog = changelogText
    type = STABLE

    // CurseForge options used by both Fabric and Forge
    def cfOptions = curseforgeOptions {
        accessToken = providers.environmentVariable("CURSEFORGEKEY")
        projectId = "357304"
        minecraftVersions.add(minecraft_version)
    }

    // Modrinth options used by both Fabric and Forge
    def mrOptions = modrinthOptions {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "S1tbzJ6Y"
        minecraftVersions.add(minecraft_version)
    }

    // FABRIC

    curseforge("curseforgeFabric") {
        displayName = "${mod_name} v${mod_version} Fabric"
        version = "${mod_version}+${minecraft_version}-Fabric"
        from cfOptions
        file project(":$mod_id-fabric")
        modLoaders.add("fabric")
        requires {
            slug = "fabric-api"
        }
    }

    modrinth("modrinthFabric") {
        displayName = "${mod_name} v${mod_version} Fabric"
        version = "${mod_version}+${minecraft_version}-Fabric"
        from mrOptions
        file project(":$mod_id-fabric")
        modLoaders.add("fabric")
        requires {
            slug = "fabric-api"
        }
    }

    // NEOFORGE

    curseforge("curseforgeNeoForge") {
        displayName = "${mod_name} v${mod_version} Neoforge"
        version = "${mod_version}+${minecraft_version}-Neoforge"
        from cfOptions
        file project(":$mod_id-neoforge")
        modLoaders.add("neoforge")
    }

    modrinth("modrinthNeoForge") {
        displayName = "${mod_name} v${mod_version} Neoforge"
        version = "${mod_version}+${minecraft_version}-Neoforge"
        from mrOptions
        file project(":$mod_id-neoforge")
        modLoaders.add("neoforge")
    }
}

tasks.publishCurseforgeNeoForge.mustRunAfter(':neoforge:publishNeoforgePublicationToMavenRepository')
tasks.publishModrinthNeoForge.mustRunAfter(':neoforge:publishNeoforgePublicationToMavenRepository')
tasks.publishCurseforgeFabric.mustRunAfter(':fabric:publishFabricPublicationToMavenRepository')
tasks.publishModrinthFabric.mustRunAfter(':fabric:publishFabricPublicationToMavenRepository')

tasks.register('buildAndReleaseNeoForge') {
    dependsOn(':neoforge:build', ':neoforge:publishNeoforgePublicationToMavenRepository', tasks.publishCurseforgeNeoForge, tasks.publishModrinthNeoForge)
}
tasks.register('buildAndReleaseFabric') {
    dependsOn(':fabric:build', ':fabric:publishFabricPublicationToMavenRepository', tasks.publishCurseforgeFabric, tasks.publishModrinthFabric)
}
tasks.register('buildAndReleaseAll') {
    dependsOn(tasks.buildAndReleaseFabric, tasks.buildAndReleaseNeoForge)
}
