plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.0.142'
    id "me.modmuss50.mod-publish-plugin" version "0.5.1"
}

apply plugin: "me.modmuss50.mod-publish-plugin"

version = "${mod_version}+${mc_version}"
group = "com.telepathicgrunt"
archivesBaseName = "${modid}-neoforge"

repositories {
    mavenLocal()
}

base {
    archivesName = modid
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        modSource project.sourceSets.main
    }

    client {
    }

    server {
        programArgument '--nogui'
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

apply from: 'gradle/manifest.gradle'
apply from: 'gradle/maven.gradle'

String changelogText = file("CHANGELOG.md").getText('UTF-8')
Map<String, String> env = System.getenv()

publishMods {
    file = jar.archiveFile
    type = STABLE

    displayName = "Structure Void Toggle v${project.mod_version} Neoforge"
    version = project.version + "_neoforge"

    changelog = changelogText
    modLoaders.add("neoforge")

    if (env.CURSEFORGEKEY) {
        curseforge {
            accessToken = env.CURSEFORGEKEY
            projectId = '357304'
            minecraftVersions.add("1.21")
        }
    }

    if (env.MODRINTH_TOKEN) {
        modrinth {
            accessToken = env.MODRINTH_TOKEN
            projectId = 'S1tbzJ6Y'
            minecraftVersions.add("1.21")
        }
    }
}

task checkForRefmap() {
    if (file("./build/libs/structure_void_toggle_neoforge-${project.mod_version}+${project.mc_version}.jar").exists()) {
        assert zipTree("./build/libs/structure_void_toggle_neoforge-${project.mod_version}+${project.mc_version}.jar")
                .matching { include "structure_void_toggle.refmap.json" }.getSingleFile() != null
    }
}

tasks.register('buildAndRelease') {}
tasks.checkForRefmap.mustRunAfter tasks.build
tasks.publish.mustRunAfter tasks.checkForRefmap
tasks.publishMods.mustRunAfter tasks.publish
tasks.buildAndRelease.dependsOn(tasks.build, tasks.checkForRefmap, tasks.publish, tasks.publishMods)