org.gradle.jvmargs=-Xmx2G

# Common
minecraft_version=1.21.5
mod_name=Structure Void Toggle
mod_author=TelepathicGrunt
mod_id=structure_void_toggle
mod_version=4.5.1
description=Make structure void less annoying to build with
display_url=https://www.curseforge.com/minecraft/mc-mods/structure-void-toggle
minecraft_version_range=[1.21.5, 1.22)

# Loaders
fabric_loader_version=0.16.10
fabric_api_version=0.119.5+1.21.5

neoforge_version=21.5.2-beta

## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.5-20250325.162830

# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21
parchment_version=2024.11.10

# Publish
maven_group=com.telepathicgrunt
publish_name=StructureVoidToggle
publish_repo=https://github.com/TelepathicGrunt/StructureVoidToggle
publish_id=telepathic_grunt
publish_author=TelepathicGrunt
publish_email=asarnesespam@gmail.com

# Note, publish_name will be project names + the modloader.