org.gradle.jvmargs=-Xmx2G

# Common
minecraft_version=1.21.4
mod_name=Structure Void Toggle
mod_author=TelepathicGrunt
mod_id=structure_void_toggle
mod_version=4.5.0
description=Make structure void less annoying to build with
display_url=https://www.curseforge.com/minecraft/mc-mods/structure-void-toggle
minecraft_version_range=[1.21.4, 1.22)

# Loaders
fabric_loader_version=0.16.9
fabric_api_version=0.111.0+1.21.4

neoforge_version=21.4.12-beta

## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.3-20241023.131943

# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.21
parchment_version=2024.11.10

# Publish
maven_group=com.telepathicgrunt
publish_name=StructureVoidToggle
publish_repo=https://github.com/TelepathicGrunt/StructureVoidToggle
publish_id=telepathic_grunt
publish_author=TelepathicGrunt
publish_email=asarnesespam@gmail.com