org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Common
minecraft_version=26.2
neoform_version=26.2-1

# NeoForge
neoforge_version=26.2.0.3-beta

# Fabric
fabric_loader_version=0.19.3
fabric_api_version=0.152.2+26.2

# MC dependencies
jetbrains_annotations_version=26.0.1
mixin_version=0.15.4+mixin.0.8.7
mixin_extras_version=0.4.1
asm_version=9.7

## Mod Properties
mod_id=structure_void_toggle
mod_name=Structure Void Toggle
mod_version=4.5.5
mod_author=TelepathicGrunt
mod_description=Make structure void less annoying to build with
sources_url=https://github.com/TelepathicGrunt/StructureVoidToggle
issues_url=https://github.com/TelepathicGrunt/StructureVoidToggle/issues
license_url=https://github.com/TelepathicGrunt/StructureVoidToggle/blob/HEAD/LICENSE.txt
homepage_url=https://www.curseforge.com/minecraft/mc-mods/structure-void-toggle

# Publishing
mod_group_id=com.telepathicgrunt
curseforge_id=357304
modrinth_id=S1tbzJ6Y