modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"

[[mods]] #mandatory
modId="structure_void_toggle" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Structure Void Toggle" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/structure-void-toggle"
authors="TelepathicGrunt"
description='''Make structure void less annoying to build with'''

[[dependencies.structure_void_toggle]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"

[[dependencies.structure_void_toggle]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.85,)"